spring:
  application:
    name: server-workers
    jobs:
      tasks:
        scheduling:
          delay: "5000"
          count: 10
        finalizing:
          delay: "5000"
          count: 10
      barriers:
        releasing:
          delay: "5000"
          count: 10

  profiles:
    default: local

  datasource:
    url: ${postgresql.url}
    username: ${postgresql.admin}
    password: ${postgresql.password}